name: Restie CI/CD
# This workflow is triggered on pushes to the repository.
on:
  push:
    paths:
     - '*'
     - '**/*'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
            node-version: 8

      - name: Install
        shell: bash
        run: npm ci
      
      - name: Test
        shell: bash
        run: npm run test
